### ISSUE TITLE
[MOI] Fix wrapper with SecondOrderCone constraints

### ISSUE THREAD

**Issue by frapac** [jump-dev/KNITRO.jl#201] opened 2021-10-08 08:46 UTC
The MOI wrapper is currently broken with `SecondOrderCone` constraints: `MOIT.test_conic` is failing, because: 
1. the primal and dual solutions have the wrong dimension 
2. the solution returned is false

**Comment by odow** [comment] 2022-08-25 23:10
Closing as duplicate of #233 There are a bunch of second order cone tests failing.

**Closed by odow** 2022-08-25 23:10 UTC
